[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[project]
name = "geopyv_dev"
version = "0.2.2"
description = "A PIV/DIC analysis package for geotechnics."
readme = "README.md"
requires-python = ">=3.8"
dependencies = ["numpy", "matplotlib", "scipy"]
authors = [
    { name = "Sam Stanier", email = "sas229@cam.ac.uk" },
    { name = "Jonathan Smith", email = "jdks2@cam.ac.uk" },
]
license = { text = "GPL-3.0-or-later" }
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Rust",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering",
]

[project.scripts]
geopyv-gui = "geopyv_dev.gui:main"

[project.optional-dependencies]
docs = [
    "sphinx>=7.0",
    "pydata-sphinx-theme>=0.15",
]

[project.urls]
"Homepage" = "https://github.com/jdks2/geopyv-dev"
"Bug Tracker" = "https://github.com/jdks2/geopyv-dev/issues"

[tool.maturin]
manifest-path = "python/Cargo.toml"
python-source = "."
module-name = "geopyv_dev._geopyv_dev"
features = ["pyo3/extension-module"]
