[package]
name = "geopyv-dev-python"
version = "0.2.2"
edition = "2021"

[lib]
name = "_geopyv_dev"
crate-type = ["cdylib"]

[dependencies]
geopyv-dev = { path = ".." }
geopyv-gui = { path = "../geopyv-gui" }
pyo3 = { version = "0.22", features = ["extension-module", "multiple-pymethods"] }
numpy = "0.22"
ndarray = "0.16"
